apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore

  target:
    name: {{ include "grafana.fullname" . }}
    creationPolicy: Owner

  data:
  - secretKey: admin-password
    remoteRef:
      key: {{ .Values.externalSecret.remotesecretname }}
      property: {{ .Values.externalSecret.remotepasswordkey }}
  - secretKey: admin-user
    remoteRef:
      key: {{ .Values.externalSecret.remotesecretname }}
      property: {{ .Values.externalSecret.remoteuserkey }}

