{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.secretProviderClass.namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    objects: |
      - objectName: "{{ .Values.secretProviderClass.objectName }}"    # Your secret name in AWS Secrets Manager
        objectType: "secretsmanager"                                  # Indicates that the object is a secret from AWS Secrets Manager
        jmesPath:
          - path: "{{ .Values.secretProviderClass.jmesPath.path }}"
            objectAlias: "{{ .Values.secretProviderClass.jmesPath.objectAlias }}"
    secretObjects:
      - secretName: {{ .Values.secretProviderClass.secretName }}
        type: Opaque
        data:
          - objectName: {{ .Values.secretProviderClass.jmesPath.objectAlias }}
            key: {{ .Values.secretProviderClass.jmesPath.path }}
{{- end }}
