apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      role: {{ .Values.secretStore.roleArn }}
      region: {{ .Values.secretStore.region }}



